name: Run Mabl test on push

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  run-mabl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Mabl test
        uses: mablhq/github-run-tests-action@v1
        with:
          mabl-api-key: ${{ secrets.MABL_API_KEY }}
          environment-id: GUleDcVXvAtpeKE5DHRgBA-e
          application-id: F9Dk1lHxAIBYIhDMj3zrYQ-a
          plan-id: RSY1O0JFkUKHmyKRHdN5tA-p
