name: Run Mabl test on push

on:
  push:
    branches:
      - main

jobs:
  run-mabl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Mabl test
        uses: mablhq/github-run-tests-action@v1
        env:
          MABL_API_KEY: Ynpe42KQAgIZalf4oz3Nfw  # Replace with your real key
        with:
          environment-id: GUleDcVXvAtpeKE5DHRgBA-e
          application-id: F9Dk1lHxAIBYIhDMj3zrYQ-a
          plan-id: RSY1O0JFkUKHmyKRHdN5tA-p
